# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_wd.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1611, 683)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon/tittle.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 0, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox.setObjectName("groupBox")
        self.open_btn = QtWidgets.QPushButton(self.groupBox)
        self.open_btn.setGeometry(QtCore.QRect(10, 20, 101, 23))
        self.open_btn.setObjectName("open_btn")
        self.convert_btn = QtWidgets.QPushButton(self.groupBox)
        self.convert_btn.setGeometry(QtCore.QRect(10, 50, 101, 23))
        self.convert_btn.setObjectName("convert_btn")
        self.open_convert_done_file_btn = QtWidgets.QPushButton(self.groupBox)
        self.open_convert_done_file_btn.setGeometry(QtCore.QRect(10, 80, 101, 23))
        self.open_convert_done_file_btn.setObjectName("open_convert_done_file_btn")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1611, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.actione_expand_all = QtWidgets.QAction(MainWindow)
        self.actione_expand_all.setObjectName("actione_expand_all")
        self.action_put_away_all = QtWidgets.QAction(MainWindow)
        self.action_put_away_all.setObjectName("action_put_away_all")
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_close)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_4.addAction(self.actione_expand_all)
        self.menu_4.addAction(self.action_put_away_all)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dbc2Excel"))
        self.groupBox.setTitle(_translate("MainWindow", "选项"))
        self.open_btn.setText(_translate("MainWindow", "打开"))
        self.convert_btn.setText(_translate("MainWindow", "转换"))
        self.open_convert_done_file_btn.setText(_translate("MainWindow", "打开转换文件"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "选择"))
        self.menu_4.setTitle(_translate("MainWindow", "查看"))
        self.menu_5.setTitle(_translate("MainWindow", "运行"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_close.setText(_translate("MainWindow", "关闭"))
        self.action_close.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.actione_expand_all.setText(_translate("MainWindow", "展开所有"))
        self.actione_expand_all.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.action_put_away_all.setText(_translate("MainWindow", "收起所有"))
        self.action_put_away_all.setShortcut(_translate("MainWindow", "Ctrl+Y"))
